package com.rajrajhans.SpringTodoApp.domain;

import javax.persistence.*;
import java.util.Set;

@Entity
public class Todo {

    @Id                             // Telling Hibernate that "id" property is the primary key
    @GeneratedValue(strategy = GenerationType.AUTO)     // Telling Hibernate that "id" is gonna be auto generated by our database
    private long id;

    private String task;

    @ManyToOne
    @JoinColumn(name="user_id")
    private User author;

    public Todo() {                 // Doing this because JPA requires a zero arg constructor
    }

    public Todo(String task, User author) {
        this.task = task;
        this.author = author;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }
}
