package com.rajrajhans.SpringTodoApp.domain;

import javax.persistence.*;
import java.util.Objects;
import java.util.Set;

@Entity
public class Todo {

    @Id                             // Telling Hibernate that "id" property is the primary key
    @GeneratedValue(strategy = GenerationType.AUTO)     // Telling Hibernate that "id" is gonna be auto generated by our database
    private long id;

    private String task;

    @ManyToOne
    @JoinColumn(name="user_id")
    private User author;

    public Todo() {                 // Doing this because JPA requires a zero arg constructor
    }

    public Todo(String task, User author) {
        this.task = task;
        this.author = author;
    }

    public String getTask() {
        return task;
    }

    public void setTask(String task) {
        this.task = task;
    }

    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    @Override
    public boolean equals(Object o) {                               // implementing a custom equals method to make sure
    if (this == o) return true;                                     // that two objects of class "User" are compared based on their ids
        if (o == null || getClass() != o.getClass()) return false;  // so that Hibernate and Set will consider two objects with same id as equal
        Todo todo = (Todo) o;
        return id == todo.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    @Override
    public String toString() {
        return "Todo{" +
                "id=" + id +
                ", task='" + task + '\'' +
                ", author=" + author +
                '}';
    }
}
